arb-dir: lib/l10n/arb
template-arb-file: app_es.arb
output-localization-file: app_localizations.dart
output-dir: lib/generated/l10n
output-class: AppLocalizations
synthetic-package: false
nullable-getter: false
use-escaping: true
